alias python='python3'
alias python3='python3'
alias pip='python3 -m pip'
alias pip3='python3 -m pip'

alias ls='exa -l -s type'
alias la='exa -al -s type'

alias ga='git add'
alias gb='git branch'
alias gc='git checkout'
alias gcb='git checkout -b'
alias gcm='git commit -m'
alias gd='git diff'
alias gst='git status'
alias gp='git push'
alias gl='git pull'
alias grhh='git reset HEAD --hard'
alias grs='git restore --staged'
alias gloga='git log --all --graph --oneline --decorate'
alias grup='git remote update --prune'
alias gsu='git submodule update --init --recursive'

alias tt='tmux attach -t'
alias tl='tmux ls'

alias add='adb devices'
alias adc='adb connect'
alias adp='adb pair'
alias ads='adb shell'
alias adk='adb kill-server'
alias addc='adb disconnect'
