alias add='adb devices'
alias adp='adb pair'
alias adc='adb connect'
alias addc='adb disconnect'
alias ads='adb shell'
alias adk='adb kill-server'

alias python='python3.8'
alias python3='python3.8'
alias pip='python3.8 -m pip'
alias pip3='python3.8 -m pip'

alias ls='exa -l -s type'
alias la='exa -al -s type'

alias ga='git add'
alias gd='git diff'
alias gb='git branch'
alias gm='git merge'
alias gaa='git add -A'
alias gst='git status'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gf='git fetch'
alias grhh='git reset HEAD --hard'
alias grup='git remote update --prune'
alias gloga='git log --all --graph --oneline --decorate'

alias tt='tmux attach -t'
alias tl='tmux ls'
