alias add='adb devices'
alias adp='adb pair'
alias adc='adb connect'
alias addc='adb disconnect'
alias ads='adb shell'
alias adk='adb kill-server'

alias python=python3
alias pip='python3 -m pip'
alias pip3='python3 -m pip'

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gf='git fetch'
alias gl='git pull'
alias gm='git merge'
alias gp='git push'
alias gcm='git commit -m'
alias gst='git status'
alias grhh='git reset HEAD --hard'
alias grup='git remote update --prune'
alias gloga='git log --all --graph --oneline --decorate'

alias tt='tmux attach -t'
alias tl='tmux ls'
